Repository DEV-TINO/Festino-App-FE, pull requests merged in 2025-03, with the labels that each got.

#182 style: change according to color theme
  public/icons/festino-icon.svg
  public/icons/festino-logo.svg
  public/icons/pin.svg
  public/icons/talent.svg
  public/images/banner/slide-banner-1.png
  public/images/banner/slide-banner-2.png
  public/images/banner/slide-banner-3.png
  public/images/booth/booth-banner.png
  public/images/booth/booth-banner.svg
  public/images/booth/booth-detail-banner.png
  public/images/booth/booth-detail-banner.svg
  public/images/teams/send.svg
  public/images/tinos/tabling-banner.svg
  public/images/tinos/tino-arm-only-4x.png
  public/images/tinos/tino-arm.png
  public/images/tinos/tino-arm4x.png
  public/images/tinos/tino-no-arm-v2.png
  public/images/tinos/tino-no-arm.png
  public/images/tinos/tino-sing.png
  public/images/tinos/tino-sing.svg
  public/images/tinos/tino-thumbs-up.png
  public/images/tinos/tino-thumbs-up.svg
  src/assets/css/tailwind.css
  src/components/Footer.vue
  src/components/booth/BoothBanner.vue
  src/components/booth/BoothInformation.vue
  src/components/booth/BoothIntroduction.vue
  src/components/booth/BoothMap.vue
  src/components/booth/BoothMenu.vue
  src/components/booth/BoothReservation.vue
  src/components/booth/DetailBanner.vue
  src/components/booth/DetailInformation.vue
  src/components/booth/MenuInformation.vue
  src/components/booth/MenuList.vue
  src/components/booth/MenuSummary.vue
  src/components/main/DateButtons.vue
  src/components/main/MainBanner.vue
  src/components/main/MainTab.vue
  src/components/main/SlideBanner.vue
  src/components/notice/Notice.vue
  src/components/notice/NoticePage.vue
  src/components/notice/PinNotice.vue
  src/components/orders/Coupon.vue
  src/components/orders/OrderDetail.vue
  src/components/orders/modals/OrderCheckModal.vue
  src/components/orders/modals/OrderDetailModal.vue
  src/components/orders/modals/OrderModal.vue
  src/components/tablings/Reservation.vue
  src/components/tablings/TablingBanner.vue
  src/components/tablings/TablingTabs.vue
  src/components/timetable/ClubModal.vue
  src/components/timetable/ShowPreview.vue
  src/components/timetable/TimeTable.vue
  src/components/timetable/TimeTableBanner.vue
  src/components/timetable/TimeTableDetail.vue
  src/views/NoticeView.vue
  src/views/NotificationView.vue
  src/views/orders/OrderMainView.vue
  tailwind.config.js
Labels: design

#184 Style: 동아리 홍보전 배치도에 맞춘 마커 위치 수정
  src/components/booth/BoothMap.vue
Labels: enhancement, design

#185 Feat : update festino spirng
  public/icons/info.svg
  public/images/banner/slide-banner-1.png
  public/images/banner/slide-banner-1.svg
  public/images/banner/slide-banner-2.png
  public/images/banner/slide-banner-2.svg
  public/images/banner/slide-banner-3.png
  public/images/banner/slide-banner-3.svg
  public/images/booth/booth-banner.svg
  public/images/booth/booth-default-image.png
  public/images/booth/booth-default-image.svg
  public/images/booth/booth-detail-banner.svg
  public/images/tinos/tabling-banner.svg
  public/images/tinos/tino-sing.svg
  src/App.vue
  src/assets/css/tailwind.css
  src/components/Footer.vue
  src/components/booth/BoothIntroduction.vue
  src/components/booth/BoothMenu.vue
  src/components/booth/MenuInformation.vue
  src/components/booth/ShowState.vue
  src/components/booth/modals/ImageDetail.vue
  src/components/main/MainTab.vue
  src/components/main/MoreButton.vue
  src/components/main/SlideBanner.vue
  src/components/notice/PinNotice.vue
  src/components/tablings/modals/TablingPreventModal.vue
  src/components/timetable/ClubModal.vue
  src/components/timetable/TimeTable.vue
  src/components/timetable/TimeTableTab.vue
  src/stores/booths/boothDataStore.js
  src/views/ModalView.vue
  tailwind.config.js
Labels: enhancement

#188 style: 부스 및 타임테이블 변경
  public/icons/booth/before/food.svg
  public/icons/booth/before/general.svg
  public/icons/booth/before/join.svg
  public/icons/booth/before/music.svg
  public/icons/booth/food.svg
  public/icons/booth/general.svg
  public/icons/booth/more.svg
  public/images/booth/booth-detail-banner.svg
  src/App.vue
  src/components/booth/BoothBanner.vue
  src/components/booth/BoothIntroduction.vue
  src/components/booth/BoothMap.vue
  src/components/booth/BoothMenu.vue
  src/components/booth/MapSpeechBubble.vue
  src/components/booth/MenuInformation.vue
  src/components/main/MainBanner.vue
  src/components/main/SlideBanner.vue
  src/components/timetable/ShowPreview.vue
  src/components/timetable/TimeTableBanner.vue
  src/components/timetable/TimeTableDetail.vue
  src/stores/booths/boothDataStore.js
Labels: enhancement, design

#191 Fix: 메뉴 아이템 수정
  src/components/booth/BoothMap.vue
  src/components/booth/MenuInformation.vue
  src/components/timetable/TimeTable.vue
Labels: enhancement, design

#193 Fix: 부스 마커 오류
  src/components/booth/BoothIntroduction.vue
  src/components/booth/BoothMap.vue
Labels: design

#195 Fix: 부스 잘못 삭제한 부분 복구
  src/components/booth/BoothMap.vue
Labels: enhancement, design

#197 푸드트럭 위치 변경
  docker-compose.yml
  docker/Dockerfile
  package-lock.json
  public/images/teams/festino.svg
  public/images/teams/people/gyeongmin.svg
  public/images/teams/people/gyuri.svg
  public/images/teams/people/huiyeon.svg
  public/images/teams/people/hyeji.svg
  public/images/teams/people/jeongyun.svg
  public/images/teams/people/jihun.svg
  public/images/teams/people/minji.svg
  public/images/teams/people/seongjun.svg
  public/images/teams/people/seungmin.svg
  public/images/teams/people/suhyeon.svg
  public/images/teams/people/taegeon.svg
  public/images/teams/people/yerin.svg
  public/images/teams/play-tino.svg
  src/components/booth/BoothMap.vue
  src/components/teams/Profile.vue
  src/views/TeamView.vue
  tailwind.config.js
  vite.config.js
Labels: design

#196 Design: 팀 소개 페이지
  docker-compose.yml
  docker/Dockerfile
  package-lock.json
  public/images/teams/festino.svg
  public/images/teams/people/gyeongmin.svg
  public/images/teams/people/gyuri.svg
  public/images/teams/people/huiyeon.svg
  public/images/teams/people/hyeji.svg
  public/images/teams/people/jeongyun.svg
  public/images/teams/people/jihun.svg
  public/images/teams/people/minji.svg
  public/images/teams/people/seongjun.svg
  public/images/teams/people/seungmin.svg
  public/images/teams/people/suhyeon.svg
  public/images/teams/people/taegeon.svg
  public/images/teams/people/yerin.svg
  public/images/teams/play-tino.svg
  src/components/teams/Profile.vue
  src/views/TeamView.vue
  tailwind.config.js
  vite.config.js
Labels: enhancement, design
